### ISSUE TITLE
optimize `zn.Method` serializer

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#192]
Currently the `zntrack.json` looks like:

```json
"npt_params": {
            "_type": "zn.method"
        }
```
and `params.yaml`
```yaml
npt_params:
        kwargs:
            barostat_factor: 500
            dump_interval: 500
            name: NVT
            pressure: 1.0
            steps: 10000
            temperature: 1100
            thermo_intervall: 1000
            timestep: 0.001
        module: main
        name: Params
```

but `module` and `name` should not be parameters and `kwargs` could be omitted.
