### ISSUE TITLE
Support plots modify or similiar

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#217]
Plots can use some additional custom configs like:

```yaml
plots:
  - plots_no_cache.csv:
      cache: false
      x: r
```

which could be achieved via `dvc plots modify plots_no_cache.csv -x r`

see for more https://dvc.org/doc/command-reference/plots/modify

Possible solutions:

- collect the command in the end and save the parameters somewhere in the descriptor.
