### ISSUE TITLE
Change in `params.yaml` might not work with `zntrack.json`

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#263]
For Example a `zn.method` being changed in the `params.yaml` can still cause issues with the wrong `zntrack.json` entry.

```yaml
ttv_train_sampler:
  groups:
  method:
  - _cls: UniformEnergetic # changed from Random
  n_configurations: 
  - 30
```

with the following `zntrack.json`

```json
"ttv_train_sampler": {
        "method": [
            {
                "_type": "zn.method",
                "value": {
                    "module": "mlsuite.configuration_selection.random"
                }
            }
        ],
```

Proposed solutions:
- ...
