### ISSUE TITLE
`meta.Environemnt` improvments

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#573]
Allow

```python
class Node:
   env: dict = meta.Environement({"OPENBLAS_NUM_THREADS": "1"})
```
and 
```
with zntrack.Project(env={"OPENBLAS_NUM_THREADS": "1"}) as project:
   ...
```
which uses `env.yaml`

```yaml
all:
  OPENBLAS_NUM_THREADS: "1"
node1: ... # does this have to be under `stages` then´ or can we assume no node is called 'all' ?
```
