### ISSUE TITLE
Combine Plots

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#589]
If one type of Node occurs multiple times, consider combining the plots automatically:

```yaml
plots:
- nodes/MLModel/training.csv:
    template: dvc_plots/templates/y_log.json
    x: epoch
    y:
    - loss
    - rmse_e_per_atom
    - rmse_f
- nodes/MLModel_1/training.csv:
    template: dvc_plots/templates/y_log.json
    x: epoch
    y:
    - loss
    - rmse_e_per_atom
    - rmse_f
- training:
      template: dvc_plots/templates/y_log.json
      x: epoch
      y:
        nodes/MLModel_1/training.csv: 
        - loss
        - rmse_e_per_atom
        - rmse_f
        nodes/MLModel/training.csv:
        - loss
        - rmse_e_per_atom
        - rmse_f
```
